name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-go:
    uses: s3ntin3l8/.github/.github/workflows/ci-go.yml@main
    with:
      coverage-fail-under: "0"
    secrets: inherit

  build-docker:
    needs: [test-go]
    permissions:
      contents: read
      packages: write
    uses: s3ntin3l8/.github/.github/workflows/docker-publish.yml@main
    with:
      image-name: "s3ntin3l8/${{ github.event.repository.name }}"
      push-edge: ${{ github.event_name == 'push' }}
    secrets: inherit
